version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/Denver"
    target-branch: "develop"
    labels:
      - "dependencies"
    reviewers:
      - "Thenlie"
      - "phillpeters"
    assignees:
      - "dependabot"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/Denver"
    target-branch: "develop"
    labels:
      - "dependencies"
    reviewers:
      - "Thenlie"
      - "phillpeters"
    assignees:
      - "dependabot"
